spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurentdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Kavija@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  address: 0.0.0.0
