spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb?useSSL=false&serverTimezone=UTC
    username: root
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
